### ISSUE TITLE
global triggers

### ISSUE THREAD

**Issue by russroy** [emyl/vagrant-triggers#13]
How difficult would it be to introduce the notion of a "global" trigger for use in multi-machine environments?   That is, a trigger which would fire once _for all_ machines rather than once _for each_ machine.    I'm thinking here of the use case of cluster-wide setup/cleanup operations.

Eg.  In an aws ec2 env I'd like to dynamically allocate a subnet for my cluster as a "before" action upon 'vagrant up'  and dealloc as an "after" action upon 'vagrant destroy' - one operation for all machines.

**Comment by AntonioMeireles** [comment]
+1 too. would be very handy.

**Comment by aprudnik** [comment]
+1. I would like it too. otherwise I have to use --no-parallel tag to ensure all VMs are up and running, after I can start a script.

**Comment by mcameron** [comment]
+1

**Comment by rolodato** [comment]
+1

**Comment by brianfgonzalez** [comment]
+1

**Comment by fabianvf** [comment]
+1, have some networking changes I need to make after every VM is up, vagrant gets very unhappy if these changes happen before it tries to bring up a vm

**Comment by stephenrlouie** [comment]
+1

**Comment by mbarretta** [comment]
+1

**Comment by ntrp** [comment]
Any news about this?

**Comment by rahulmishra** [comment]
+1
