### ISSUE TITLE
Display / capture coloured output in post-provision run

### ISSUE THREAD

**Issue by madAndroid** [emyl/vagrant-triggers#26]
Firstly, great plugin, thanks very much for putting this together!

I'm currently using this to implement ServerSpec tests directly following a successful puppet provisioning run ... and it would be awesome if the plugin were able to maintain/preserve the coloured output of the ServerSpec run, to make the output easier to read at first glance. We use the standard shell provisioner to execute the puppet run, and this preserves the coloured output of puppet's resource management.

The Vagrant documentation suggests setting `keep_color` bool to `true` to preserve the native script output colour, and this appears to be the default .. is there perhaps a way to default this to true for the vagrant-trigger run as well?

Is this a feature that you would potentially support at some point? If the behaviour I'm experiencing is not expected, are there any configuration options I can set to ensure coloured output is preserved?

Thanks in advance :)

**Comment by emyl** [comment]
Hello,

I know it's an old thread, but I've finally made some efforts trying to reproduce the issue. Unfortunately everything looks good to me, as you can see from the following screenshot:

![screenshot 2016-03-28 20 37 43](https://cloud.githubusercontent.com/assets/562707/14086407/41e5ef78-f525-11e5-85f9-24dd13af171a.png)

If you're still interested in the issue and you have a reproducible case, could you please share it?
