### ISSUE TITLE
Run Cookbooks On Up?

### ISSUE THREAD

**Issue by bassrock** [emyl/vagrant-triggers#38]
Hi,

I was curious if it is possible to run specific cookbooks on a vagrant up. These would be tasks that are required to run every time a machine is brought up, not just on a provision.

**Comment by emyl** [comment]
Hi!

Not sure if this plugin is the best choice for what you want to achieve, probably you should use two different provision blocks and play with the `run: always` option. Here some docs:

https://docs.vagrantup.com/v2/provisioning/basic_usage.html
