### ISSUE TITLE
Destroy trigger fired before confirmation

### ISSUE THREAD

**Issue by mmrose** [emyl/vagrant-triggers#40]
I defined a destroy trigger like this:

``` ruby
    config.trigger.before :destroy, :stdout => true, :stderr => true do
        run_remote "/vagrant/cleanup.sh"
    end
```

This leads to `cleanup.sh` being called right before confirmation. 

Do you see any way to get the trigger called only if confirmation is given or `--force` is used?

**Comment by albrin** [comment]
How do I understand this bug is not resolved?
