### ISSUE TITLE
:stderr, :stdout defaults to false when using config.vm.provision "trigger"

### ISSUE THREAD

**Issue by tbal** [emyl/vagrant-triggers#42]
Hi,

first of all, thanks for the great plugin!

The documentation states:
* ```:stderr => true|false```: display standard error from scripts. Defaults to true.
* ```:stdout => true|false```: display standard output from scripts. Defaults to true.

I'm using the following setup:
```ruby
  config.vm.provision "trigger" do |trigger|
    trigger.fire do
      run "uname -a"
    end 
  end 
```

I got no output at all unless explicitly setting the options stdout and/or stderr to true:
```ruby
  config.vm.provision "trigger", :stdout => true, :stderr => true do |trigger|
```

Vagrant 1.7.2
vagrant-triggers 0.5.0

Does the documentation need an update or is this a bug?

**Comment by emyl** [comment]
Hi!

That's a :bug: 

Going to fix it in the next release. Thanks!
