### ISSUE TITLE
Cannot use builtin commands (e.g. "if") on Windows hosts

### ISSUE THREAD

**Issue by mbrodala** [emyl/vagrant-triggers#43]
To reduce the noise when trying to re-mount an existing share drive (see #27), I'd like to make it conditional. This is what I tried:

```ruby
config.trigger.after :up do
  # Mount network share after startup
  run "if not exist Z: net use /y Z: \\\\192.168.33.10\\webroot"
end
```

This yields the following error:

> The executable "if" Vagrant is trying to trigger
> was not found. If you know it is not in the PATH, please
> specify its absolute path using the :append_to_path option.

Sure, `if` is no command (executable) but a builtin. Thus I tried with a sub-process:

```ruby
config.trigger.after :up do
  # Mount network share after startup
  run 'cmd /c "if not exist Z: net use /y Z: \\\\192.168.33.10\\webroot"'
end
```

But this gives me the following error:

> The command "cmd /c "if not exist Z: net use /y Z: \\192.168.33.10\webroot"" returned a failed exit
> code. The error output is shown below:
> Syntax error.

Executing `cmd /c "if not exist Z: net use /y Z: \\192.168.33.10\webroot"` within a command prompt works perfectly fine though.

Any idea what's wrong here?

**Comment by colegatron** [comment]
Other user reported issues using "run" and was successful using "system" instead. 
Maybe it helps.

**Comment by mbrodala** [comment]
You mean like in #53? I'll give it a try.

**Comment by mbrodala** [comment]
Works flawlessly, thanks for the hint. :-)

**Comment by jerturowetz** [comment]
I stumbled on this issue trying to resolve using 'cd' in an inline script 

which generates the same error on windows
