### ISSUE TITLE
Current working directory of triggered script is not the location of the Vagrantfile

### ISSUE THREAD

**Issue by jfly** [emyl/vagrant-triggers#44]
Vagrant allows you to run "vagrant ..." from any directory, and it will search upwards to find the nearest `Vagrantfile`. I've written my trigger scripts assuming that the current working directory is the same directory as my `Vagrantfile`, but that appears to not be the case. Here's my workaround:

```ruby
  config.trigger.before [:reload, :up, :provision], stdout: true do
    Dir.chdir '..' while !File.exist?('Vagrantfile')
    ...
  end
```

**Comment by emyl** [comment]
Hi!

Marked as :bug: 

Going to fix in the next release! Thanks!
