### ISSUE TITLE
"run" Command Hangs When Subprocess Waits For User Input

### ISSUE THREAD

**Issue by jpotterm** [emyl/vagrant-triggers#53]
I have a Vagrantfile that contains the following:

``` ruby
config.vm.provision "trigger" do |trigger|
    trigger.fire do
        run "read"
    end
end
```

When I run `vagrant provision` it waits for input forever even when I type and hit enter.

If I use Ruby's `system` command instead, everything works as expected:

``` ruby
config.vm.provision "trigger" do |trigger|
    trigger.fire do
        system("read")
    end
end
```

Tested with vagrant-triggers 0.5.2

**Comment by vinnyrose** [comment]
:+1:
