### ISSUE TITLE
How to triggers a command after rsync-auto

### ISSUE THREAD

**Issue by byteshiva** [emyl/vagrant-triggers#56]
How to trigger a command after rsync-auto

```
$vagrant rsync-auto
```
I'm looking for the below vagrant dsl to execute whenever there happens an rsync between host to guest.  

But the below script is not working !!
```
config.trigger.after :rsync do
        run "pwd"
  end
```

**Comment by emyl** [comment]
Hello,

Unfortunately such a trigger can't currently work, see also #36 for more details.
