### ISSUE TITLE
Trigger for "box update"

### ISSUE THREAD

**Issue by rustybailey** [emyl/vagrant-triggers#57]
Is it possible to hook into the various "box" commands? We would like to have a trigger for `vagrant box update`, but that doesn't seem to be possible.

**Comment by emyl** [comment]
Hello,

It's not currently possible, since an [action hook](https://www.vagrantup.com/docs/plugins/action-hooks.html) is not defined for that machine action.

If that action hook should be implemented in upstream vagrant, the plugin would start hooking automatically.

Cheers :smiley:
