### ISSUE TITLE
End-users cannot intuitively discover what triggers are available to use?  

### ISSUE THREAD

**Issue by mlintonford** [emyl/vagrant-triggers#69]
Apart from the up, destroy, halt, and resume shown in Readme.md, end-users cant intuitively discover triggers.

Could be solved by link to some type of triggers list in vagrant github

**Comment by javadevmtl** [comment]
Yes. I'm trying different actions and they don't seem to fire.

Does it also mean the third party provisioner like the vSphere vagrant also have to implement the action?

**Comment by brianfgonzalez** [comment]
+1
