### ISSUE TITLE
run_remote via triggers for user other than root

### ISSUE THREAD

**Issue by anujsrc** [emyl/vagrant-triggers#80]
## Environment
* Vagrant: 1.9.1
* Triggers: 0.5.3
* Vagrant Box: ubuntu/xenial64

## Issue
Trying to run a script under /vagrant that is owned by the ubuntu user. Also, there are additional environment settings including password-less SSH for ubuntu user. Triggers are fired via root user that may not get those environment variables and other SSH settings of ubuntu user hence the script fails to execute due to component level errors but the trigger does get fired correctly.

## Query
Is there a way to run the triggers as a specific user?

**Comment by anujsrc** [comment]
Currently, I am using the ``run`` directive to achieve this-
```
 run "ssh -F vagrant-ssh default '/vagrant/start.sh'"
```
where, ``vagrant-ssh`` is vagrant ssh config-

```
vagrant ssh-config > vagrant-ssh
```
If there is a better way, do let me know. Thanks.

**Comment by marcrohloff** [comment]
I agree it would be nice to have this as an option to `run_remote`. I used 
```
run_remote 'sudo -u vagrant -H /vagrant/start,sh'
```

You should be able to use
```
run 'vagrant ssh -c /vagrant/start.sh'
```
