### ISSUE TITLE
Critical Failure with Vagrant v1.9.6, v1.9.7

### ISSUE THREAD

**Issue by nachopants** [emyl/vagrant-triggers#89]
vagrant plugin install vagrant-triggers
Installing the 'vagrant-triggers' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies rb-fsevent (= 0.9.8) and rb-fsevent (= 0.10.2)
  Activated rb-fsevent-0.10.2
  which does not match conflicting dependency (= 0.9.8)

  Conflicting dependency chains:
    rb-fsevent (= 0.10.2), 0.10.2 activated

  versus:
    rb-fsevent (= 0.9.8)

  Gems matching rb-fsevent (= 0.9.8):
    rb-fsevent-0.9.8

**Comment by emyl** [comment]
I'm sorry but I can't reproduce the issue:

![image](https://user-images.githubusercontent.com/562707/29004368-829fb06c-7ac6-11e7-8aef-270fa10d5c0c.png)

If you have additional details feel free to share. Thanks.
