### ISSUE TITLE
Ability to run a process in the background

### ISSUE THREAD

**Issue by mbarretta** [emyl/vagrant-triggers#91]
Was trying something like

```
config.trigger.after [:up, :resume] do
    run "my_long_running_process.sh &"
end
```
...expecting the background flag to force the trigger execution to exit, but it continues "Executing command" forever.

**Comment by daverogers** [comment]
I got one to work like this:

```
config.trigger.after :up do
    `(vagrant rsync-auto &>/dev/null) &`
end
```

**Comment by agriffis** [comment]
This is [tricky to do right](http://blog.n01se.net/blog-n01se-net-p-145.html)

It would be better for vagrant-triggers to provide a `run_bg` command so callers don't have to muddle through the formula
